on: push
name: Lint Python
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Self test
          id: selftest
          uses: ryan-rozario/pipreqs-action-cpy@master
